### ISSUE TITLE
Question about the filtering links

### ISSUE THREAD

**Issue by abitdodgy** [nateberkopec/todomvc-turbolinks#2]
Why not use view helpers [on line 47 of index.html.erb][1]? For example:

```slim
= link_to "Completed", params.merge(complete: false), class: ('selected' if params[:completed] == 'false')
```

Instead of...

```erb
<a id="active" href="/?completed=false" class="<%= "selected" if request.fullpath.match("completed=false") %>">Active</a>
```
Is it a matter of preference or are you trying to gain some performance?

[1]: https://github.com/nateberkopec/todomvc-turbolinks/blob/master/app/views/todos/index.html.erb#L47

**Comment by nateberkopec** [comment]
*Definitely* just silly coding. I don't believe there is any performance advantage to be gained in not using link helpers - and if there was, you should just cache the results instead of *not using* the helper.
